defaults:
  bus_addr: "48"
  adc_id: "ads1115_${bus_addr}"
  gain: "4.096"
  update_interval_soil_humidity: 10sec
  channel: "0"
  name_prefix: ""
  on_value_script: "default_on_value_script"

sensor:
  - platform: ads1115
    ads1115_id: ${adc_id}
    gain: ${gain}
    multiplexer: A${channel}_GND
    name: ${adc_id}_${channel}
    id: ${adc_id}_${channel}
    update_interval: ${update_interval_soil_humidity}
    on_value:
      then:
          - delay: 100ms
          - script.execute: "${on_value_script}"

