defaults:
  co2_i2c_bus: i2c_bus_0
  update_interval_rht_co2: 10sec
  co2_address: "0x61"
  id_prefix: ""

sensor:
  - platform: scd30
    id: rhtco2
    co2:
      id: ${id_prefix}air_co2
      name: ${id_prefix}air_co2
      accuracy_decimals: 1
    temperature:
      id: ${id_prefix}air_temperature
      name: ${id_prefix}air_temperature
      accuracy_decimals: 2
    humidity:
      id: ${id_prefix}air_humidity
      name: ${id_prefix}air_humidity
      accuracy_decimals: 1
  #    temperature_offset: 1.5 °C
    address: ${co2_address}
    i2c_id: ${co2_i2c_bus}
    update_interval: ${update_interval_rht_co2}
