defaults:
  one_wire_bus: onewire_23
  update_interval_ds_temp: 10sec
  id_prefix: ""
  i: ""
#  address_hex:

sensor:
  - platform: dallas_temp
    one_wire_id: ${one_wire_bus}
    id: ${id_prefix}${i}
    name: ${id_prefix}${i}
    address: 0x${address_hex}
    update_interval: ${update_interval_ds_temp}

text_sensor:
  - platform: template
    id: ${id_prefix}${i}_addr
    name: ${id_prefix}${i}_addr
    lambda: return {"${address_hex}"};