defaults:
  id_prefix: "fan"
  ctrl_pin: "GPIO26"
  sense_pin: "GPIO14"
  min_power: "10%"
  ui_update_script: "default_on_value_script"

#packages:
#  lvgl_status_fans: !include
#    file: ../../common/ui/fans_status.yaml

globals:
  - id: "globals_${id_prefix}_pwm_setpoint"
    type: float
    initial_value: '0.0'
    restore_value: no


output:
  - platform: ledc
    pin: ${ctrl_pin}
    id: output_${id_prefix}_pwm
    frequency: "25000 Hz"
    min_power: ${min_power}
    max_power: 100%
    zero_means_zero: true

number:
  - platform: template
    id: number_${id_prefix}_pwm
    name: ${id_prefix}_pwm
    min_value: 0.0
    max_value: 1.0
    step: 0.0001
    set_action:
      then:
        - output.set_level:
            id: output_${id_prefix}_pwm
            level: !lambda "return x;"
        - globals.set:
            id: "globals_${id_prefix}_pwm_setpoint"
            value: !lambda "return x;"
        - script.execute: "${ui_update_script}"

sensor:
  - platform: pulse_meter
    id: ${id_prefix}_rpm
    name: ${id_prefix}_rpm
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    timeout: 1s
    pin:
      number: ${sense_pin}
      inverted: true
      mode:
        input: true
    #        pullup: true
    filters:
      - multiply: 0.5
      - throttle_average: 1s
    on_value:
      then:
        - script.execute: "${ui_update_script}"
