defaults:
  update_interval_uptime: 10sec


sensor:
  - platform: uptime
    id: dev_uptime
    name: dev_uptime
    update_interval: ${update_interval_uptime}

text_sensor:
  - platform: version
    id: dev_version
    name: dev_version
