defaults:
  update_interval_wifi: 10sec


wifi:
  domain: ".local"
  networks:
    - ssid: !secret wifi_test_ssid
      password: !secret wifi_test_password
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2


  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "${device_name} Hotspot"
#    password: !secret ap_password
#  captive-portal:


sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: wifi_signal_db
    name: wifi_signal_db
    update_interval: ${update_interval_wifi}
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    id: wifi_signal_percent
    name: wifi_signal_percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""


text_sensor:
  - platform: wifi_info
    ip_address:
      id: net_ip
      name: net_ip
      address_0:
        id: net_ip_0
        name: net_ip_0
      address_1:
        id: net_ip_1
        name: net_ip_1
    ssid:
      id: net_wifi_ssid
      name: net_wifi_ssid
    bssid:
      id: net_wifi_bssid
      name: net_wifi_bssid
    mac_address:
      id: net_wifi_mac
      name: net_wifi_mac
    scan_results:
      id: net_wifi_networks
      name: net_wifi_networks
    dns_address:
      id: net_ip_dns
      name: net_ip_dns

